"""drop all tables

Revision ID: 27bb1d6d46e3
Revises: 54b7e804654d
Create Date: 2026-01-28 15:13:25.971018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27bb1d6d46e3'
down_revision: Union[str, Sequence[str], None] = '54b7e804654d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_run')
    op.drop_table('run_state')
    op.drop_table('pr_snapshot')
    op.drop_table('pull_request')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pull_request',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('repo_full_name', sa.String(), nullable=False),
        sa.Column('pr_number', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('repo_full_name', 'pr_number', name='uq_pr_identity'),
    )
    op.create_index(op.f('ix_pull_request_pr_number'), 'pull_request', ['pr_number'], unique=False)
    op.create_index(op.f('ix_pull_request_repo_full_name'), 'pull_request', ['repo_full_name'], unique=False)
    op.create_table(
        'pr_snapshot',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pr_id', sa.Integer(), nullable=False),
        sa.Column('head_sha', sa.String(), nullable=False),
        sa.Column('pr_body_sha256', sa.String(), nullable=False),
        sa.Column('policy_version', sa.String(), nullable=False),
        sa.Column('pr_title', sa.String(), nullable=False),
        sa.Column('changed_files', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('user_risk', sa.String(), nullable=True),
        sa.Column('backout_text_hash', sa.String(), nullable=True),
        sa.Column('backout_text', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['pr_id'], ['pull_request.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('pr_id', 'head_sha', 'pr_body_sha256', 'policy_version', name='uq_pr_snapshot'),
    )
    op.create_index(op.f('ix_pr_snapshot_head_sha'), 'pr_snapshot', ['head_sha'], unique=False)
    op.create_index(op.f('ix_pr_snapshot_policy_version'), 'pr_snapshot', ['policy_version'], unique=False)
    op.create_index(op.f('ix_pr_snapshot_pr_body_sha256'), 'pr_snapshot', ['pr_body_sha256'], unique=False)
    op.create_index(op.f('ix_pr_snapshot_pr_id'), 'pr_snapshot', ['pr_id'], unique=False)
    op.create_table(
        'run_state',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('repo_full_name', sa.String(), nullable=False),
        sa.Column('pr_number', sa.Integer(), nullable=False),
        sa.Column('latest_evaluation_key', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('reason_codes', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('system_risk', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('pr_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['pr_id'], ['pull_request.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('repo_full_name', 'pr_number', name='uq_run_state'),
    )
    op.create_index(op.f('ix_run_state_pr_id'), 'run_state', ['pr_id'], unique=False)
    op.create_index(op.f('ix_run_state_pr_number'), 'run_state', ['pr_number'], unique=False)
    op.create_index(op.f('ix_run_state_repo_full_name'), 'run_state', ['repo_full_name'], unique=False)
    op.create_table(
        'evaluation_run',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('evaluation_key', sa.String(), nullable=False),
        sa.Column('snapshot_id', sa.Integer(), nullable=False),
        sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_ts', sa.DateTime(timezone=True), nullable=True),
        sa.Column('policy_risk', sa.String(), nullable=True),
        sa.Column('llm_risk', sa.String(), nullable=True),
        sa.Column('system_risk', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('reason_codes', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('llm_model', sa.String(), nullable=True),
        sa.Column('llm_prompt_version', sa.String(), nullable=True),
        sa.Column('state_json', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['snapshot_id'], ['pr_snapshot.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_evaluation_run_evaluation_key'), 'evaluation_run', ['evaluation_key'], unique=True)
    op.create_index(op.f('ix_evaluation_run_snapshot_id'), 'evaluation_run', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###
