"""Add owner repo pr_number

Revision ID: 4d9e1c0a276c
Revises: b0d44836e7d2
Create Date: 2026-02-08 13:18:43.404353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9e1c0a276c'
down_revision: Union[str, Sequence[str], None] = 'b0d44836e7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_run', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('evaluation_run', sa.Column('repo', sa.String(), nullable=True))
    op.add_column('evaluation_run', sa.Column('pr_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_evaluation_run_owner'), 'evaluation_run', ['owner'], unique=False)
    op.create_index(op.f('ix_evaluation_run_pr_number'), 'evaluation_run', ['pr_number'], unique=False)
    op.create_index(op.f('ix_evaluation_run_repo'), 'evaluation_run', ['repo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_run_repo'), table_name='evaluation_run')
    op.drop_index(op.f('ix_evaluation_run_pr_number'), table_name='evaluation_run')
    op.drop_index(op.f('ix_evaluation_run_owner'), table_name='evaluation_run')
    op.drop_column('evaluation_run', 'pr_number')
    op.drop_column('evaluation_run', 'repo')
    op.drop_column('evaluation_run', 'owner')
    # ### end Alembic commands ###
