"""change_status_to_string

Revision ID: 5f0b7f3e6d62
Revises: 045dfc6da1ea
Create Date: 2026-02-06 21:07:47.936532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f0b7f3e6d62'
down_revision: Union[str, Sequence[str], None] = '045dfc6da1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluation_run', 'status',
               existing_type=postgresql.ENUM('PROCESSING', 'ACTION_REQUIRED', 'DONE', 'ERROR', name='evaluationstatus'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluation_run', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PROCESSING', 'ACTION_REQUIRED', 'DONE', 'ERROR', name='evaluationstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
